// Generated by scripts/gen-schema.mjs — the one definition both sides share.
export const COLUMNS = {
  "Projects": [
    "id",
    "name_bn",
    "client_bn",
    "ptype",
    "area_sqft",
    "budget",
    "start_date",
    "plan_days",
    "status",
    "updated_at"
  ],
  "Workers": [
    "id",
    "name_bn",
    "rate",
    "phone",
    "active",
    "updated_at"
  ],
  "Items": [
    "id",
    "name_bn",
    "unit_bn",
    "last_rate",
    "active",
    "updated_at"
  ],
  "Parties": [
    "id",
    "name_bn",
    "ptype",
    "terms_days",
    "phone",
    "updated_at"
  ],
  "Stages": [
    "id",
    "project_type",
    "seq",
    "name_bn",
    "weight",
    "updated_at"
  ],
  "Coefficients": [
    "id",
    "project_type",
    "item_id",
    "per_sqft",
    "updated_at"
  ],
  "Bills": [
    "id",
    "name_bn",
    "to_bn",
    "amount",
    "due_date",
    "repeat",
    "personal",
    "paid_on",
    "note",
    "updated_at"
  ],
  "Day": [
    "id",
    "batch",
    "date",
    "project_id",
    "cash_counted",
    "cash_computed",
    "note",
    "reverses",
    "created_at"
  ],
  "Attendance": [
    "id",
    "batch",
    "date",
    "project_id",
    "worker_id",
    "presence",
    "days",
    "rate",
    "amount",
    "advance",
    "reverses",
    "created_at"
  ],
  "Stock": [
    "id",
    "batch",
    "date",
    "project_id",
    "item_id",
    "dir",
    "qty",
    "rate",
    "amount",
    "party_id",
    "due_date",
    "paid",
    "photo_id",
    "reverses",
    "created_at"
  ],
  "Money": [
    "id",
    "batch",
    "date",
    "project_id",
    "head_bn",
    "dir",
    "amount",
    "party_id",
    "mode",
    "note",
    "personal",
    "photo_id",
    "reverses",
    "created_at"
  ],
  "Progress": [
    "id",
    "batch",
    "date",
    "project_id",
    "stage_seq",
    "state",
    "pct",
    "reverses",
    "created_at"
  ]
}

export const APPEND_TABS = ["Day","Attendance","Stock","Money","Progress"]
