-- Generated by scripts/gen-schema.mjs from src/lib/model.ts — do not edit by hand.

CREATE TABLE IF NOT EXISTS households (
  id           TEXT PRIMARY KEY,
  name         TEXT NOT NULL,
  device_token TEXT NOT NULL UNIQUE,
  created_at   TEXT NOT NULL
);

-- The nightly file, kept beside the data it describes so the app fetches
-- both from one origin.
CREATE TABLE IF NOT EXISTS briefs (
  household_id TEXT NOT NULL PRIMARY KEY,
  body         TEXT NOT NULL,
  generated_at TEXT NOT NULL,
  received_at  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS projects (
  household_id TEXT NOT NULL,
  name_bn      TEXT,
  client_bn    TEXT,
  ptype        TEXT,
  area_sqft    REAL,
  budget       REAL,
  start_date   TEXT,
  plan_days    REAL,
  status       TEXT,
  updated_at   TEXT,
  id           TEXT NOT NULL,
  received_at  TEXT NOT NULL,
  PRIMARY KEY (household_id, id)
);

CREATE TABLE IF NOT EXISTS workers (
  household_id TEXT NOT NULL,
  name_bn      TEXT,
  rate         REAL,
  phone        TEXT,
  active       INTEGER,
  updated_at   TEXT,
  id           TEXT NOT NULL,
  received_at  TEXT NOT NULL,
  PRIMARY KEY (household_id, id)
);

CREATE TABLE IF NOT EXISTS items (
  household_id TEXT NOT NULL,
  name_bn      TEXT,
  unit_bn      TEXT,
  last_rate    REAL,
  active       INTEGER,
  updated_at   TEXT,
  id           TEXT NOT NULL,
  received_at  TEXT NOT NULL,
  PRIMARY KEY (household_id, id)
);

CREATE TABLE IF NOT EXISTS parties (
  household_id TEXT NOT NULL,
  name_bn      TEXT,
  ptype        TEXT,
  terms_days   REAL,
  phone        TEXT,
  updated_at   TEXT,
  id           TEXT NOT NULL,
  received_at  TEXT NOT NULL,
  PRIMARY KEY (household_id, id)
);

CREATE TABLE IF NOT EXISTS stages (
  household_id TEXT NOT NULL,
  project_type TEXT,
  seq          REAL,
  name_bn      TEXT,
  weight       REAL,
  updated_at   TEXT,
  id           TEXT NOT NULL,
  received_at  TEXT NOT NULL,
  PRIMARY KEY (household_id, id)
);

CREATE TABLE IF NOT EXISTS coefficients (
  household_id TEXT NOT NULL,
  project_type TEXT,
  item_id      TEXT,
  per_sqft     REAL,
  updated_at   TEXT,
  id           TEXT NOT NULL,
  received_at  TEXT NOT NULL,
  PRIMARY KEY (household_id, id)
);

CREATE TABLE IF NOT EXISTS bills (
  household_id TEXT NOT NULL,
  name_bn      TEXT,
  to_bn        TEXT,
  amount       REAL,
  due_date     TEXT,
  repeat       TEXT,
  personal     INTEGER,
  paid_on      TEXT,
  note         TEXT,
  updated_at   TEXT,
  id           TEXT NOT NULL,
  received_at  TEXT NOT NULL,
  PRIMARY KEY (household_id, id)
);

CREATE TABLE IF NOT EXISTS day (
  household_id TEXT NOT NULL,
  batch        TEXT,
  date         TEXT,
  project_id   TEXT,
  cash_counted REAL,
  cash_computed REAL,
  note         TEXT,
  reverses     TEXT,
  created_at   TEXT,
  id           TEXT NOT NULL,
  received_at  TEXT NOT NULL,
  PRIMARY KEY (household_id, id)
);
CREATE INDEX IF NOT EXISTS ix_day_hd ON day (household_id, date);
CREATE INDEX IF NOT EXISTS ix_day_hp ON day (household_id, project_id);

CREATE TABLE IF NOT EXISTS attendance (
  household_id TEXT NOT NULL,
  batch        TEXT,
  date         TEXT,
  project_id   TEXT,
  worker_id    TEXT,
  presence     TEXT,
  days         REAL,
  rate         REAL,
  amount       REAL,
  advance      REAL,
  reverses     TEXT,
  created_at   TEXT,
  id           TEXT NOT NULL,
  received_at  TEXT NOT NULL,
  PRIMARY KEY (household_id, id)
);
CREATE INDEX IF NOT EXISTS ix_attendance_hd ON attendance (household_id, date);
CREATE INDEX IF NOT EXISTS ix_attendance_hp ON attendance (household_id, project_id);

CREATE TABLE IF NOT EXISTS stock (
  household_id TEXT NOT NULL,
  batch        TEXT,
  date         TEXT,
  project_id   TEXT,
  item_id      TEXT,
  dir          TEXT,
  qty          REAL,
  rate         REAL,
  amount       REAL,
  party_id     TEXT,
  due_date     TEXT,
  paid         INTEGER,
  photo_id     TEXT,
  reverses     TEXT,
  created_at   TEXT,
  id           TEXT NOT NULL,
  received_at  TEXT NOT NULL,
  PRIMARY KEY (household_id, id)
);
CREATE INDEX IF NOT EXISTS ix_stock_hd ON stock (household_id, date);
CREATE INDEX IF NOT EXISTS ix_stock_hp ON stock (household_id, project_id);

CREATE TABLE IF NOT EXISTS money (
  household_id TEXT NOT NULL,
  batch        TEXT,
  date         TEXT,
  project_id   TEXT,
  head_bn      TEXT,
  dir          TEXT,
  amount       REAL,
  party_id     TEXT,
  mode         TEXT,
  note         TEXT,
  personal     INTEGER,
  photo_id     TEXT,
  reverses     TEXT,
  created_at   TEXT,
  id           TEXT NOT NULL,
  received_at  TEXT NOT NULL,
  PRIMARY KEY (household_id, id)
);
CREATE INDEX IF NOT EXISTS ix_money_hd ON money (household_id, date);
CREATE INDEX IF NOT EXISTS ix_money_hp ON money (household_id, project_id);

CREATE TABLE IF NOT EXISTS progress (
  household_id TEXT NOT NULL,
  batch        TEXT,
  date         TEXT,
  project_id   TEXT,
  stage_seq    REAL,
  state        TEXT,
  pct          REAL,
  reverses     TEXT,
  created_at   TEXT,
  id           TEXT NOT NULL,
  received_at  TEXT NOT NULL,
  PRIMARY KEY (household_id, id)
);
CREATE INDEX IF NOT EXISTS ix_progress_hd ON progress (household_id, date);
CREATE INDEX IF NOT EXISTS ix_progress_hp ON progress (household_id, project_id);
