/* English for every word the app shows.

   The key is the Bengali string exactly as it is written in the screens, so a
   missing entry falls back to Bengali rather than to a blank or a key name.
   {0}, {1} are the runtime values; keep them, and move them where English
   word order wants them.

   The words are trade English as it is spoken on a site in West Bengal —
   "mistri", "rate", "godown" — not textbook English. Numbers, money and dates
   are handled in bn.ts, not here. */

export const EN: Record<string, string> = {
  /* ---- shell, buttons, common words ---- */
  'সাইট খাতা': 'Site Khata',
  'আজকের হিসাব': "Today's entry",
  'আজকের হিসাব লেখা হল': "Today's entry saved",
  'আজকের হিসাব লেখা হয়েছে — আরও যোগ করতে পারেন': 'Written for today — you can still add more',
  'কয়েকটা প্রশ্ন, তারপর শেষ': 'A few questions, then done',
  'কালকের মতোই': 'Same as yesterday',
  'দোকানের মজুত': 'Shop stock',
  'নিজের খরচ': 'Personal spending',
  'নতুন কাজের হিসাব': 'Estimate a job',
  'পুরোনো হিসাব': 'Past entries',
  'সেটিংস': 'Settings',
  'ফিরে': 'Back',
  'ফিরে যান': 'Go back',
  'আগের ধাপ': 'Previous step',
  'বন্ধ করুন': 'Close',
  'এগিয়ে যান': 'Next',
  'হয়ে গেল': 'Done',
  'সেভ করুন': 'Save',
  'সেভ হচ্ছে…': 'Saving…',
  'সেভ হয়েছে': 'Saved',
  'যোগ করুন': 'Add',
  'বাতিল করুন': 'Cancel',
  'বাদ দিন': 'Skip',
  'থাক': 'Leave it',
  'থাক, পরে': 'Later',
  'মুছুন': 'Clear',
  'একটা মুছুন': 'Delete one',
  'নতুন': 'New',
  'আরও': 'More',
  'আরও…': 'More…',
  'আরও কিছু আছে?': 'Anything else?',
  'আরও মাল': 'More material',
  'আরও খরচ': 'More expenses',
  'হ্যাঁ': 'Yes',
  'না': 'No',
  'শুরু করি': "Let's start",
  'শুরু হল — এবার আজকের হিসাব লিখুন': "Ready — now write today's entry",
  'নতুন করে আনুন': 'Refresh',
  'কপি হয়েছে': 'Copied',
  'জন': 'men',
  '{0} জন': '{0} men',
  '{0} টি নাম': '{0} names',
  'হাতে': 'in hand',
  'কম': 'less',
  'বেশি': 'more',
  'মোট': 'Total',
  'ফারাক': 'Difference',
  'চলছে': 'running',
  'শেষ': 'finished',
  'ধরন': 'Type',
  'নাম': 'Name',
  'ফোন': 'Phone',
  'অবস্থা': 'Status',
  'কী': 'What',
  'কীভাবে': 'How',
  'নমুনা': 'Sample',

  /* ---- home: sections and status ---- */
  'কাজ': 'Work',
  'মজুত': 'Inventory',
  'হিসাব': 'Accounts',
  'সকাল': 'morning',
  'দুপুর': 'afternoon',
  'সন্ধে': 'evening',
  'রাতের হিসাব': "Last night's brief",
  'রাতের হিসাব এসে গেছে': 'The nightly brief has arrived',
  'রাতের হিসাব এখনও তৈরি হয়নি': 'The nightly brief is not ready yet',
  'ফোনের নিজের হিসাব': "The phone's own sums",
  'নিচের সংখ্যাগুলো ফোনের নিজের হিসাব।': "The numbers below are the phone's own sums.",
  'নজর দেওয়ার মতো': 'Worth a look',
  'কাজের অবস্থা': 'Where the work stands',
  'খরচ আর পরিকল্পনা': 'Spend against plan',
  'মাল কত গেল': 'Material used',
  'যা করতে হবে': 'To do',
  'এক নজরে': 'At a glance',
  'খরচ': 'Spend',
  'শেষ হিসাব': 'Last entry',
  'মাঝের দিনগুলো লিখতে চাইলে ‘পুরোনো হিসাব’ থেকে তারিখ বেছে নিন।': 'To fill the days in between, pick a date under Past entries.',
  'এখনও কোনো কাজ যোগ করা হয়নি। কাজ এলে এখানে অগ্রগতি আর খরচ পাশাপাশি দেখা যাবে।': 'No job added yet. Once there is one, progress and spend show side by side here.',
  'কাজ আর লোক': 'Jobs and men',
  'যোগ করা, বদলানো': 'Add, edit',
  'মালের তালিকা': 'Item list',
  'নাম, একক, শেষ দর': 'Name, unit, last rate',
  'দর দেওয়ার আগে': 'Before you quote',
  'আলাদা খাতা': 'A separate book',
  'দেখা ও সংশোধন': 'View and correct',
  'মাল ঢোকা, বিক্রি, গোনা': 'Goods in, sale, count',
  'শুধু ফোনে রাখা হচ্ছে': 'Kept on this phone only',
  'সব খাতায় উঠে গেছে': 'Everything is on the server',
  'লাইন পাঠানো বাকি': 'rows still to send',
  'নেট এলে যাবে': 'will go when the network returns',
  'গত সাত দিনে': 'In the last seven days',
  'দিন হিসাব লেখা হয়েছে': 'days were written',
  'মজুতের দাম': 'Stock value',
  'রকম মাল': 'kinds of goods',
  '{0} রকম মাল': '{0} kinds of goods',
  '{0} রকম মাল · {1}': '{0} kinds · {1}',
  '{0} রকম': '{0} kinds',
  'দোকানে বাকি': 'Owed to suppliers',
  'সময় পেরিয়েছে': 'overdue',
  '{0} সময় পেরিয়েছে': '{0} overdue',
  'সময়ের মধ্যে': 'within time',
  'এখন যা আছে': 'What is in stock now',
  'দরে': 'at',
  'রকম মাল শেষ বা মাইনাসে — একবার গুনে নিন।': 'kinds are out of stock or negative — do a count.',
  'কাকে কত দিতে হবে': 'Who has to be paid',
  'মোট বাকি': 'Total owed',
  'নাম লেখা নেই': 'No name written',
  'হাতে টাকা': 'Cash in hand',
  'শেষ গোনা থেকে': 'since the last count',
  'একবার গুনে বসিয়ে দিন': 'Count it once and enter it',
  'এ মাসের খরচ': "This month's spend",
  'এ মাসে খরচ': 'Spent this month',
  'চলতি মাস': 'this month',
  'বাকি দেনা': 'Outstanding dues',
  '{0} দিন আগে গোনা': 'counted {0} days ago',
  'তিন দিন কোনো হিসাব লেখা হয়নি।': 'Nothing has been written for three days.',
  '{0} দেনার সময় পেরিয়ে গেছে।': '{0} of dues is past its date.',
  'এ সপ্তাহে {0} দিতে হবে।': '{0} has to be paid this week.',
  '{0}: কাজের তুলনায় খরচ বেশি হচ্ছে।': '{0}: spending is running ahead of the work.',
  'সব ঠিক চলছে।': 'Everything is on track.',
  'একটা কাজ যোগ করে শুরু করুন।': 'Add a job to get started.',
  'দোকান': 'Shop',

  /* ---- onboarding ---- */
  'খাতাটা এবার ফোনে': 'The ledger, now on your phone',
  'রোজ সন্ধেবেলা কয়েকটা প্রশ্নের উত্তর দিলেই দিনের হিসাব লেখা হয়ে যাবে। যত ব্যবহার করবেন, তত কম টিপতে হবে — অ্যাপ আপনার নিজের অভ্যাস দেখে আগেভাগে ভরে দেবে।':
    "Answer a few questions each evening and the day is written. The more you use it, the less you tap — it learns your habits and fills things in ahead of you.",
  'সাইটের লোক, মাল, খরচ আর অগ্রগতি': 'Men on site, material, spending and progress',
  'দোকানে কী ঢুকল, কী বিক্রি হল, কী পড়ে আছে': 'What came in, what sold, what is left',
  'হাতে কত, কাকে কত দিতে হবে, মাসে কত গেল': 'Cash in hand, who is owed, what the month cost',
  'নেট না থাকলেও পুরোটা চলে। কোনো নাম-পাসওয়ার্ড লাগে না। কোনো হিসাব মুছে যায় না — ভুল হলে উল্টো লাইন লেখা হয়।':
    'It works with no network. No account, no password. Nothing is ever deleted — a mistake is fixed by writing the opposite entry.',
  'কোন ভাষায় দেখতে চান?': 'Which language do you want?',
  'পরে যখন খুশি বদলানো যাবে — সেটিংস থেকে।': 'You can change this any time in Settings.',
  'বাংলা': 'Bengali',
  'সংখ্যাও বাংলায় — ১,২৫০': 'Bengali numerals too — ১,২৫০',
  'আপনার নাম?': 'What is your name?',
  'শুধু ডাকার জন্য — খাতার উপরে দেখাবে।': 'Only to greet you — it shows at the top of the ledger.',
  'কী কী চালান?': 'What do you run?',
  'যেটা চালান না, সেটাও থাকবে — শুধু পরে দেখাবে।': 'What you do not run stays available — it just sits further down.',
  'সাইটের কাজ': 'Site work',
  'ঠিকাদারি, বাড়ি তোলা': 'Contracts, building houses',
  'মাল কেনা-বেচা, মজুত': 'Buying, selling, stock',
  'এখন কোন কাজটা চলছে?': 'Which job is running now?',
  'একটা নাম দিলেই হবে — যেমন ‘রামপুর বাড়ি’। এখন কোনো কাজ না থাকলে ছেড়ে দিন, পরে যোগ করা যাবে।':
    "A name is enough — 'Rampur house', say. If there is no job right now, leave it; you can add one later.",
  'এখন কোনো কাজ নেই': 'No job right now',
  'কাজের নাম': 'Job name',
  'চুক্তির টাকা (জানা থাকলে)': 'Contract amount (if you know it)',
  'চুক্তির টাকা': 'Contract amount',
  'এটা থাকলে খরচ আর কাজের তুলনা দেখানো যায়।': 'With this, spend can be compared against progress.',
  'কারা কাজ করে?': 'Who works for you?',
  'নাম আর রোজ। যতজন মনে আছে দিন, বাকিরা পরে যোগ হবে।': 'Name and daily rate. Add whoever comes to mind; the rest can follow later.',
  '+ আরও একজন': '+ One more',
  'রোজ': 'Daily rate',
  'রোজ কত': 'Daily rate',
  'এই মুহূর্তে হাতে কত টাকা আছে?': 'How much cash is in hand right now?',
  'না জানলে ছেড়ে দিন — যেদিন গুনবেন, সেদিন থেকেই মিলতে শুরু করবে।': 'Leave it if you do not know — it starts matching from the day you first count.',
  'এটা একবার বসালে রোজকার শেষে ‘হাতে কত’ নিজে থেকেই মিলে যাবে।': 'Enter it once and the end-of-day cash works itself out.',

  /* ---- the day wizard ---- */
  'কোন কাজ?': 'Which job?',
  'আজ কে কে এসেছে?': 'Who came in today?',
  'মজুরি কত দিলেন?': 'What did you pay them?',
  'মাল এসেছে?': 'Any material in?',
  'আর কোনো খরচ?': 'Any other spending?',
  'কাজ কতদূর?': 'How far has the work got?',
  'দিনের শেষে হাতে কত?': 'How much cash at the end of the day?',
  'একবার দেখে নিন': 'Have a look before saving',
  '+ নতুন কাজ': '+ New job',
  'কোনো কাজ চলছে না': 'No job running',
  'শুধু দোকান আর হাতের হিসাব': 'Just the shop and the cash',
  'নতুন কাজ': 'New job',
  'কার কাজ (ইচ্ছে হলে)': 'Whose job (optional)',
  'যেমন — রামপুর বাড়ি': 'e.g. Rampur house',
  'যেমন — শ্রী অমিত ঘোষ': 'e.g. Amit Ghosh',
  'যেমন — সিমেন্ট': 'e.g. Cement',
  'যেমন — বিকেলে বৃষ্টিতে কাজ বন্ধ': 'e.g. Rain stopped work in the afternoon',
  'গতবারের মতো টিক দেওয়া আছে। যে আসেনি তার টিক তুলে দিন।': 'Ticked as last time. Untick anyone who did not come.',
  'যারা এসেছে তাদের টিক দিন।': 'Tick whoever came in.',
  'কোনো লোক যোগ করা নেই। সেটিংস থেকে লোক যোগ করুন।': 'No men added yet. Add them from Settings.',
  'পুরো দিন': 'Full day',
  'আধা দিন': 'Half day',
  'ওভারটাইম': 'Overtime',
  'ওভারটাইম (দেড় দিন)': 'Overtime (one and a half days)',
  '{0} রোজ': '{0} a day',
  'অগ্রিম': 'Advance',
  '· অগ্রিম {0}': '· advance {0}',
  'কেউ আসেনি, তাই মজুরি নেই।': 'Nobody came, so there are no wages.',
  'রোজ অনুযায়ী হিসাব করা আছে। আলাদা দিলে সেই লাইনে চাপ দিন।': 'Worked out from the daily rates. Tap a line if you paid something different.',
  'আজকের মজুরি': "Today's wages",
  'মোট মজুরি': 'Total wages',
  'মজুরি': 'Wages',
  'মজুরি ও বাকি': 'Wages and advances',
  'আজ কোনো মাল এলে এখানে লিখুন।': 'If any material came in today, write it here.',
  'কী মাল?': 'Which material?',
  'কোন মাল?': 'Which item?',
  'কত {0}?': 'How many {0}?',
  '{0} গুনে কত {1}?': 'Counted {0} — how many {1}?',
  'কত দর?': 'What rate?',
  'কত দরে বিক্রি?': 'Sold at what rate?',
  'কোন দামে ধরব?': 'At what price should it go in?',
  'গতবার {0} প্রতি {1}': 'Last time {0} per {1}',
  'গতবার {0} প্রতি {1} · {2}': 'Last time {0} per {1} · {2}',
  'প্রথমবার': 'First time',
  'প্রথমবার — যা দিলেন লিখুন।': 'First time — write what you paid.',
  'টাকা দিয়েছেন?': 'Have you paid?',
  'হ্যাঁ, দিয়েছি': 'Yes, paid',
  'না, বাকি': 'No, on credit',
  'হিসাবে বাকি হিসেবে থাকবে।': 'It will stay in the books as a due.',
  '{0} — {1} দিনের মধ্যে, অর্থাৎ {2}।': '{0} — within {1} days, that is {2}.',
  'কার কাছ থেকে': 'From whom',
  'কার কাছ থেকে?': 'From whom?',
  'কাকে বিক্রি?': 'Sold to whom?',
  'বিলের ছবি': 'Photo of the bill',
  'বিলের ছবি (ইচ্ছে হলে)': 'Photo of the bill (optional)',
  'বিলের ছবি নেওয়া হয়েছে': 'Bill photo taken',
  'ছবি নেওয়া হয়েছে': 'Photo taken',
  'কীসের খরচ?': 'Spent on what?',
  'কত টাকা?': 'How much?',
  'কীভাবে দিলেন': 'How did you pay',
  'মজুরি এখানে লিখবেন না — সেটা আগের পাতায় হিসাব হয়ে গেছে।': 'Do not write wages here — they were counted on the previous screen.',
  'গাড়ি ভাড়া, মেশিন, চা — মজুরি আর মাল ছাড়া বাকি সব।': 'Transport, machine hire, tea — everything other than wages and material.',
  'আজকের মোট খরচ': "Today's total spend",
  'কিছু লিখে রাখবেন? (ইচ্ছে হলে)': 'Want to note anything? (optional)',
  'কাজের অগ্রগতি': 'Progress',
  'এখন চলছে —': 'Running now —',
  'শতকরা কত হল সেটা আপনাকে আন্দাজ করতে হবে না — ধাপের ওজন থেকে নিজে থেকে হিসাব হয়ে যায়।':
    'You do not have to guess a percentage — it works itself out from the weight of each stage.',
  '{0} — অর্ধেক হয়েছে': '{0} — half done',
  '{0} — শেষ হয়েছে': '{0} — finished',
  'কাল থেকে {0}': 'From tomorrow, {0}',
  'কাজ শেষের দিকে': 'The job is near its end',
  'আজ বদল নেই': 'No change today',
  'একটা ধাপ শেষ': 'A stage finished',
  'অর্ধেক হয়েছে': 'Half done',
  'ধাপ শেষ': 'Stage done',
  'অর্ধেক': 'Half',
  'এই কাজের ধাপগুলো এখনও ঠিক করা হয়নি। সেটিংস → ধাপ থেকে একবার ঠিক করে নিলে এখানে কাজের অগ্রগতি নিজে থেকেই হিসাব হবে।':
    'The stages for this job are not set yet. Set them once under Settings → Stages and progress works itself out here.',
  'আপনি গুনে বললেন': 'You counted and said',
  'খাতার হিসাবে এখন থাকার কথা': 'By the books there should be',
  'খাতায় ছিল': 'The books said',
  'গুনে পাওয়া গেল': 'Counted',
  'গুনে কত হল?': 'What did the count come to?',
  'গুনে বলছি': 'Let me count',
  'না, গুনে বলছি': 'No, let me count',
  'হ্যাঁ, এটাই আছে': 'Yes, that is what is there',
  'ঠিক আছে, এগোই': 'Fine, carry on',
  'আবার গুনি': 'Count again',
  'মিলিয়ে নিন': 'Check it',
  'দিনের শেষে': 'End of the day',
  'প্রথমবার — একবার গুনে বলে দিন, তারপর থেকে অ্যাপ নিজেই হিসাব রাখবে।': 'First time — count once, and after that the app keeps track itself.',
  'কিছু আসেনি': 'nothing came in',
  'কিছু নেই': 'nothing',
  'অন্য খরচ': 'Other spending',
  'মাল': 'Material',
  'আজ কিছুই লেখা হয়নি। এভাবে সেভ করলে শুধু ‘আজ কাজ হয়নি’ লেখা থাকবে।': "Nothing has been entered. Saving now records only that no work happened today.",
  'বাকি প্রশ্নগুলো যোগ করা হল': 'The remaining questions have been added',
  'নতুন মাল': 'New item',
  'নতুন মাল যোগ করুন': 'Add a new item',
  'মালের নাম': 'Item name',
  'কীসের হিসাবে': 'Counted in',
  'চেনা তালিকা থেকে বেছে নিন': 'Pick from the common list',
  'চেনা তালিকায় যা মিলল': 'Matches in the common list',
  'চেনা তালিকায় এই নামে কিছু নেই — উপরের ‘যোগ করুন’ টিপলেই নিজের নামে যোগ হয়ে যাবে।':
    'Nothing by that name in the common list — press Add above and it goes in under your own name.',
  'পাইপ, ফিটিংস, ভালভ, বাথরুম, বিদ্যুৎ — মাপ ইঞ্চিতে': 'Pipes, fittings, valves, bathroom, electrical — sizes in inches',
  'পাইপ, ফিটিংস, ভালভ, বাথরুম, বিদ্যুৎ — মাপ ইঞ্চিতে। নাম টিপে বসালেই খোঁজাও যায়।':
    'Pipes, fittings, valves, bathroom, electrical — sizes in inches. Type a name to search.',
  '+ চেনা তালিকা থেকে যোগ করুন': '+ Add from the common list',
  'নতুন দোকান': 'New supplier',
  'নতুন খদ্দের': 'New customer',
  '+ নতুন দোকান': '+ New supplier',
  '+ দোকান যোগ করুন': '+ Add a supplier',
  '+ নতুন মাল': '+ New item',
  '+ নতুন': '+ New',
  'সব দোকান': 'All suppliers',
  'সব মাল': 'All items',
  'সব খরচের খাত': 'All expense heads',
  'কত দিনের বাকিতে দেয় (না জানলে ০)': 'How many days of credit (0 if unsure)',
  'কত দিনের বাকিতে দেয়': 'Days of credit',
  '{0} দিনের বাকি': '{0} days credit',
  'খদ্দের': 'Customer',
  'খুচরো খদ্দের': 'Walk-in customer',
  'খদ্দেরের নাম': 'Customer name',
  'যেগুলো বেশি আনেন সেগুলো আগে দেখানো হচ্ছে।': 'The ones you buy most are shown first.',

  /* ---- shop ---- */
  'মাল এসেছে': 'Goods in',
  'বিক্রি হয়েছে': 'Sold',
  'কাজে পাঠানো': 'Sent to site',
  'মাল গোনা': 'Stock count',
  'দোকানে ঢুকল': 'came into the shop',
  'খদ্দেরকে': 'to a customer',
  'দামে নয়, খরচে': 'at cost, not at price',
  'যা আছে মিলিয়ে নিন': 'Check what is there',
  'দোকানে এত নেই। মজুত মাইনাসে চলে যাবে — আগে ‘মাল গোনা’ করে নিন।':
    'There is not that much in the shop. Stock will go negative — do a count first.',
  'কাজে পাঠানো মাল কেনা দামেই ধরা হয় — তাতে দোকানের লাভ আর কাজের খরচ, দুটোই ঠিক থাকে।':
    'Material sent to a site goes in at cost — that keeps both the shop profit and the job cost honest.',
  'এখনও কোনো মাল ঢোকেনি।': 'No goods have come in yet.',
  'এখনও কোনো মাল ঢোকেনি। ‘মাল এসেছে’ থেকে শুরু করুন।': 'No goods yet. Start from Goods in.',
  '‘মাল এসেছে’ থেকে শুরু করুন।': 'Start from Goods in.',
  'কেনা': 'bought',
  'বাকিতে কেনা': 'bought on credit',
  'বিক্রি': 'sold',
  'গোনা': 'counted',
  'কোন কাজে?': 'For which job?',

  /* ---- personal book ---- */
  'পাসকোড': 'Passcode',
  'পাসকোড দিন': 'Enter the passcode',
  'নতুন পাসকোড': 'New passcode',
  'আরেকবার দিন': 'Enter it again',
  'পাসকোড সেভ হয়েছে': 'Passcode saved',
  'মিলছে না': 'Does not match',
  'মিলল না, আবার দিন।': 'Did not match — try again.',
  'এই খাতা শুধু আপনার।': 'This book is yours alone.',
  'চার সংখ্যার একটা কোড। ভুলে গেলে সেটিংস থেকে বদলাতে হবে।': 'A four-digit code. If you forget it, change it from Settings.',
  'ঘরের জন্য টাকা': 'Money for the household',
  'ব্যবসা থেকে নিলাম': 'Taken from the business',
  'ব্যবসা থেকে নেওয়া': 'Drawn from the business',
  'ব্যবসা থেকে নেওয়া টাকা ব্যবসার খরচ নয় — তাই কাজের হিসাবে এটা ধরা হয় না, শুধু হাতের টাকা কমে।':
    'Money drawn from the business is not a business expense — it never touches a job, it only reduces cash in hand.',
  'ব্যবসার হাতের টাকা থেকে এই টাকাটা কমে যাবে।': 'This comes off the cash in hand.',
  'খরচ লিখুন': 'Write the expense',
  'লেখা হল': 'Written',
  'এ মাসের হিসাব': "This month's book",
  'এ মাসে এখনও কিছু লেখা হয়নি।': 'Nothing written this month yet.',
  'নিজের খাতা': 'Personal book',
  'বাজার': 'Groceries',
  'বাজার, ওষুধ, বিল': 'Groceries, medicine, bills',
  'ওষুধ': 'Medicine',
  'পড়াশোনা': 'Education',
  'যাতায়াত': 'Travel',
  'অনুষ্ঠান': 'Functions',
  'বিদ্যুৎ বিল': 'Electricity bill',
  'মেরামত': 'Repairs',
  'অন্যান্য': 'Other',

  /* ---- estimator ---- */
  'দর তৈরি করুন': 'Build a quote',
  'কী ধরনের কাজ?': 'What kind of job?',
  'কত স্কোয়ার ফুট?': 'How many square feet?',
  'মাপ (বর্গফুট)': 'Area (sqft)',
  'মোট বিল্ট-আপ মাপ। পরে বদলাতে পারবেন।': 'Total built-up area. You can change it later.',
  'কত দিনে শেষ করার কথা': 'How many days to finish',
  'ওভারহেড %': 'Overhead %',
  'লাভ %': 'Profit %',
  'মালের হিসাব': 'Material estimate',
  'দর জানা নেই': 'rate not known',
  'এই ধরনের জন্য কোনো থাম্ব রুল বসানো নেই।': 'No thumb rules are set for this kind of job.',
  'সেটিংস → ধাপ ও থাম্ব রুল থেকে একবার বসিয়ে নিলে এই হিসাব কাজ করবে।': 'Set them once under Settings → Stages and thumb rules and this works.',
  'এখনও কোনো ধরন ঠিক করা নেই।': 'No job type has been set up yet.',
  'দরপত্র': 'Quotation',
  'দরপত্র · {0}': 'Quotation · {0}',
  'কাজ: {0} · {1} বর্গফুট': 'Job: {0} · {1} sqft',
  'খদ্দের: {0}': 'Customer: {0}',
  '{0} · {1} বর্গফুট': '{0} · {1} sqft',
  'মাল ও সরঞ্জাম     {0}': 'Material and fittings     {0}',
  'মজুরি             {0}': 'Labour             {0}',
  'ওভারহেড {0}%      {1}': 'Overhead {0}%      {1}',
  'লাভ {0}%           {1}': 'Profit {0}%           {1}',
  'মোট               {0}': 'Total               {0}',
  'প্রতি বর্গফুট       {0}': 'Per sqft       {0}',
  'শর্ত: মাল ও মজুরির দর বদলালে হিসাব বদলাতে পারে। কাজ শুরুর আগে ৩০% অগ্রিম।':
    'Terms: the figure can change if material or labour rates change. 30% advance before work starts.',
  'এটা কপি করে WhatsApp-এ পাঠাতে পারেন। ছাপা কাগজ লাগলে কম্পিউটার থেকে Google Sheet-এর হিসাব ব্যবহার করুন।':
    'Copy this and send it on WhatsApp. For a printed sheet, use the ledger on a computer.',
  'ঠিকা কাজ': 'Contract work',

  /* ---- history ---- */
  'কোন দিনের হিসাব?': 'Which day?',
  'তারিখ বেছে নিন': 'Pick a date',
  'যে দিনটা বাদ পড়ে গেছে সেটা বেছে নিন।': 'Pick the day that was missed.',
  'দিনের হিসাব': "The day's entry",
  '{0} দিনের লেখা': '{0} days written',
  '{0} · {1} লাইন': '{0} · {1} rows',
  'এই দিনে শুধু ‘কাজ হয়নি’ লেখা আছে।': 'This day says only that no work happened.',
  'আজ আলাদা কিছু হয়নি': 'Nothing separate today',
  'এখনও কিছু লেখা হয়নি।': 'Nothing has been written yet.',
  'সংশোধন': 'Correct',
  'সংশোধন লেখা হল': 'Correction written',
  'এই লাইনটা বাতিল করবেন?': 'Cancel this row?',
  'কোনো লাইন মুছে ফেলা হয় না — ভুল হলে তার উল্টো লাইন লেখা হয়, তাই খাতায় সব ইতিহাস থেকে যায়।':
    'No row is ever deleted — a mistake is cancelled by writing its mirror, so the history stays whole.',
  'চলতি মাসে {0}': '{0} this month',

  /* ---- settings ---- */
  'হিসাবের জিনিসপত্র': 'The books',
  'টাকা ও খাতা': 'Money and ledger',
  'দেখা ও পড়া': 'Display and reading',
  'নিজের জন্য': 'For you',
  'লোকজন': 'Men',
  'দোকান ও খদ্দের': 'Suppliers and customers',
  'কাজের ধাপ ও থাম্ব রুল': 'Stages and thumb rules',
  'ধাপ ও থাম্ব রুল': 'Stages and thumb rules',
  'হাতের টাকা': 'Cash in hand',
  'অনলাইন খাতা': 'Online ledger',
  'জোড়া লাগানো আছে': 'connected',
  'ব্যাকআপ': 'Backup',
  'ফোনে একটা কপি রেখে দিন': 'Keep a copy on the phone',
  'নিজের খরচের পাসকোড': 'Passcode for personal spending',
  'দেওয়া আছে': 'set',
  'দেওয়া নেই': 'not set',
  'লেখার আকার ও রং': 'Text size and colour',
  'লেখার আকার': 'Text size',
  'ফোনের মতো': 'Same as phone',
  'আলো': 'Light',
  'অন্ধকার': 'Dark',
  'ছোট': 'Small',
  'সাধারণ': 'Normal',
  'বড়': 'Large',
  'আরও বড়': 'Larger',
  'বাছাই ঠিক হচ্ছে?': 'Are the suggestions landing?',
  'তিন ভাগের এক ভাগের বেশি সময় পুরো তালিকা খুলতে হচ্ছে — বাছাইয়ের নিয়মটা ঠিক করা দরকার।':
    'The full list is being opened more than a third of the time — the ranking needs work.',
  'বেশির ভাগ সময় প্রথম তিনটে চিপেই কাজ হয়ে যাচ্ছে।': 'Most of the time the first three chips are enough.',
  'সার্ভারের ঠিকানা': 'Server address',
  'গোপন টোকেন': 'Secret token',
  'পরীক্ষা করুন': 'Test',
  'দেখছি…': 'Checking…',
  'যোগাযোগ ঠিক আছে': 'Connection is fine',
  'পাঠানো বাকি': 'Waiting to be sent',
  'এখনই পাঠান': 'Send now',
  '{0} লাইন পাঠানো হল': '{0} rows sent',
  'হিসাব প্রথমে ফোনে লেখা হয়, তারপর নেট পেলে নিজে থেকেই অনলাইনে চলে যায়। ঠিকানা না দিলেও অ্যাপ পুরোপুরি চলে — তখন খাতাটা শুধু এই ফোনেই থাকে।':
    'Entries are written to the phone first and go online by themselves when there is a network. With no address the app still works fully — the ledger simply stays on this phone.',
  'এই টোকেন দিয়ে শুধু এই খাতায় লেখা আর পড়া যায় — আর কারও হিসাব নয়, আর মুছে ফেলাও যায় না।':
    'This token can only read and append to this one ledger — no one else’s, and it can delete nothing.',
  'এখন আনুন': 'Fetch now',
  'আনছি…': 'Fetching…',
  'এখনও আসেনি': 'not arrived yet',
  'নতুন ফোনে': 'On a new phone',
  'ফোন হারালে বা বদলালে — নতুন ফোনে এই একই ঠিকানা আর টোকেন বসিয়ে নিচের বোতামটা টিপুন। যা যা অনলাইনে গিয়েছিল, সব ফিরে আসবে। এই ফোনে যা আছে তা মুছবে না।':
    'If the phone is lost or replaced, put the same address and token into the new one and press the button below. Everything that reached the server comes back. Nothing on this phone is erased.',
  'অনলাইন থেকে ফিরিয়ে আনুন': 'Restore from the server',
  'অনলাইন থেকে ফিরিয়ে আনবেন?': 'Restore from the server?',
  'যা যা অনলাইনে আছে সব এই ফোনে যোগ হবে। এই ফোনের কোনো লেখা মুছবে না।': 'Everything on the server is added to this phone. Nothing here is erased.',
  'ফিরিয়ে আনুন': 'Restore',
  'নামছে…': 'Downloading…',
  '{0} লাইন ফিরে এসেছে': '{0} rows restored',
  'স্প্রেডশিটের জন্য (CSV)': 'For a spreadsheet (CSV)',
  'Excel বা Google Sheet-এ খোলে': 'Opens in Excel or Google Sheets',
  'পুরো কপি (JSON)': 'Full copy (JSON)',
  'সব কিছু, হুবহু': 'Everything, exactly as it is',
  'পুরো খাতাটা একটা ফাইলে বেরিয়ে আসে, ফোনের Documents ফোল্ডারে। মাসে একবার করে রাখলে ফোন হারালেও হিসাব থাকে।':
    'The whole ledger comes out as one file in the phone’s Documents folder. Do it once a month and a lost phone costs you nothing.',
  'রাখা হল — {0}': 'Saved — {0}',
  'রাখা গেল না': 'Could not save',
  'শুরুর টাকা': 'Opening cash',
  'সেভ করলে আজ থেকে এই সংখ্যাটাই ধরা হবে।': 'Once saved, this is the figure counted from today.',
  'রোজকার হিসাবের শেষে টাকা গুনলে এই সংখ্যাটা নিজে থেকেই ঠিক হয়ে যায়। প্রথম দিনের জন্য শুধু একবার শুরুর টাকাটা বসিয়ে দিন।':
    'Counting the cash at the end of a day fixes this figure by itself. For the first day, just enter the opening amount once.',
  'শেষ গোনা হয়েছিল {0}, তখন ছিল {1}।': 'Last counted {0}, and it was {1} then.',
  'এখন হিসাবমতো': 'By the books now',
  'কাজ করছে': 'working',
  'এখন কাজ করছে না': 'not working now',
  'নতুন লোক': 'New man',
  'যাদের রোজ মজুরি দেন তাদের একবার বসিয়ে নিন।': 'Enter the men you pay a daily wage once.',
  'মাল কেনার সময় নতুন নাম যোগ করা যায় — আগে থেকে বসাতেই হবে এমন নয়।': 'New names can be added while buying — nothing has to be set up in advance.',
  'মাল কেনার সময় দোকানের নাম যোগ করা যায়।': 'Supplier names can be added while buying.',
  'শেষ দর': 'Last rate',
  'খদ্দের লেখা নেই': 'no customer written',
  'এখনও চলছে': 'still running',
  'একটা কাজ যোগ করুন — তারপর রোজকার হিসাব শুরু।': 'Add a job — then the daily entries begin.',
  'কাজের ধাপ বসানো না থাকলে অগ্রগতি হিসাব হয় না।': 'Without stages, progress cannot be worked out.',
  'ঘর তৈরির চেনা ধাপ বসিয়ে দিন': 'Use the usual house-building stages',
  'ঘর তৈরির চেনা ধাপ বসানো হল — নিজের মতো বদলে নিন': 'The usual stages are in — change them to suit your work',
  'ধাপ': 'stages',
  '{0}টা ধাপ': '{0} stages',
  '{0}টা চলছে': '{0} running',
  'ধাপের নাম': 'Stage name',
  'ওজন (সব মিলিয়ে ১০০)': 'Weight (100 in total)',
  'প্রতি বর্গফুটে': 'per sqft',
  'প্রতি বর্গফুটে কত': 'How much per sqft',
  'কিছু বসানো নেই।': 'Nothing set.',
  'ধাপের ওজন মিলে ১০০ হলে ‘কাজ কতদূর’ থেকে শতকরা নিজে থেকেই বেরোয়। থাম্ব রুল দিয়ে নতুন কাজের হিসাব হয় — কাজ শেষে আসল খরচ দেখে এগুলো ঠিক করে নেবেন।':
    'When the stage weights add to 100, progress works itself out. The thumb rules drive new estimates — correct them from what a finished job actually consumed.',

  /* ---- sync and errors ---- */
  'সেটিংসে ঠিকানা দেওয়া নেই': 'No server address in Settings',
  'সার্ভার {0}': 'Server {0}',
  'সার্ভার মানল না': 'The server refused it',
  'উত্তর বোঝা গেল না': 'Could not read the reply',
  'টোকেন মিলল না': 'Token did not match',
  'জোড়া লাগল না': 'Could not connect',
  'সময় শেষ': 'Timed out',
  'সময় শেষ, আবার চেষ্টা হবে': 'Timed out — it will try again',
  'নেট পাওয়া যাচ্ছে না': 'No network',
  'পাঠানো গেল না': 'Could not send',
  'পাঠান': 'Send',
  'ব্রিফ আনা গেল না': 'Could not fetch the brief',
  'ব্রিফ পাওয়া গেল না ({0})': 'Could not fetch the brief ({0})',
  'ব্রিফের ফাইলটা ঠিক নেই': 'The brief file is not right',

  /* ---- project status flags ---- */
  'ঠিক আছে': 'On track',
  'খরচ কাজের অনেক আগে': 'Spend far ahead of work',
  'খরচ কাজের থেকে এগিয়ে': 'Spend ahead of work',
  'খরচ কম, কাজ এগিয়ে': 'Work ahead of spend',

  /* ---- charts ---- */
  '{0} দিন · {1} / {2} লাখ': 'Day {0} · {1} / {2} lakh',
  '{0} লাখ খরচ': '{0} lakh spent',
  'পরিকল্পনার তুলনায় খরচ — এখন {0} {1}': 'Spend against plan — now {0} {1}',
  '— — পরিকল্পনা': '— — plan',
  '—— আসল খরচ': '—— actual',
  'খাড়া দাগটা কাজের অগ্রগতি': 'The upright line is how far the work has got',
  'দিন': 'days',

  /* ---- payment modes and expense heads (shown, never stored in English) ---- */
  'নগদ': 'Cash',
  'ব্যাংক': 'Bank',
  'চেক': 'Cheque',
  'গাড়ি ভাড়া': 'Transport',
  'মেশিন ভাড়া': 'Machine hire',
  'চা-জলখাবার': 'Tea and food',
  'যন্ত্রপাতি': 'Tools',
  'বিদ্যুৎ-জল': 'Power and water',
  'সরকারি খরচ': 'Government charges',

  /* ---- seeded stages of a house ---- */
  'ঘর': 'House',
  'ভিত ও মাটি কাটা': 'Excavation and footing',
  'ফাউন্ডেশন ও কলাম': 'Foundation and columns',
  'প্লিন্থ ঢালাই': 'Plinth casting',
  'দেওয়াল গাঁথনি': 'Brickwork',
  'ছাদ ঢালাই': 'Roof casting',
  'প্লাস্টার': 'Plaster',
  'দরজা-জানালা, লাইন': 'Doors, windows, lines',
  'রং ও ফিনিশিং': 'Paint and finishing',

  /* ---- months and days (dates are built in bn.ts, these are for chips) ---- */
  'আজ': 'Today',
  'গতকাল': 'Yesterday',
  'পরশু': 'Day before',
  'আগামীকাল': 'Tomorrow',
  'এইমাত্র': 'just now',

  /* ---- language switch ---- */
  'ভাষা': 'Language',
  'একই খাতা, একই সংখ্যা — শুধু লেখাগুলো বদলায়। যা লিখে রেখেছেন, যেমন লোকের নাম বা মালের নাম, সেগুলো যেমন লিখেছেন তেমনই থাকে।':
    "The same ledger and the same numbers — only the words change. What you typed yourself, like a man's name or an item name, stays exactly as you wrote it.",

  /* ---- money owed and owing ---- */
  'টাকা দেওয়া-নেওয়া': 'Payments',
  'বাকি মেটানো, পাওনা তোলা': 'Settle bills, collect dues',
  'বাকি মেটানো': 'Bill settled',
  'পাবেন': 'To get',
  'দেবেন': 'To pay',
  'দেবেন {0} · পাবেন {1}': 'To pay {0} · to get {1}',
  'কারও কাছে বাকি নেই, কারও কাছে পাওনাও নেই।': 'Nothing owed, nothing owing.',
  'যাদের দিতে হবে': 'Suppliers to pay',
  'যাদের কাছে পাওনা': 'Customers who owe you',
  '{0} থেকে বাকি — সময় পেরিয়েছে': 'Owed since {0} — overdue',
  '{0} তারিখে দিতে হবে': 'Due on {0}',
  '{0} থেকে পাওনা — সময় পেরিয়েছে': 'Owing since {0} — overdue',
  '{0} তারিখে পাওয়ার কথা': 'Due from them on {0}',
  '{0} — {1} দেওয়া হল': '{0} — paid {1}',
  '{0} — {1} পাওয়া গেল': '{0} — received {1}',
  'টাকা দিলাম': 'I paid',
  'টাকা পেলাম': 'I received',
  '{0} — বাকি {1}': '{0} — owed {1}',
  '{0} — পাওনা {1}': '{0} — owing {1}',
  'বাকির চেয়ে বেশি লিখছেন। বাড়তি টাকাটা পরের বিলের জমা হিসেবে থেকে যাবে।':
    'That is more than the balance. The extra stays as credit against the next bill.',
  'কবেকার': 'For which day',
  'টাকা পেয়েছেন?': 'Have you been paid?',
  'বাকিতে বিক্রি হলে খদ্দেরের নাম দিন — নইলে কার কাছে পাওনা তা আর মনে থাকবে না।':
    'On a credit sale, name the customer — otherwise there is no telling who owes it.',
  'কবেকার হিসাব?': 'Which day is this?',
  'লেখা হচ্ছে {0} · এখনকার সময় ধরে রাখা হবে': 'Writing it under {0} · the clock time is kept as now',
  '{0} তারিখে': 'on {0}',
  '{0} দরে': 'at {0}',
  'দোকানে আছে {0} {1}': 'In the shop: {0} {1}',

  /* ---- reminders ---- */
  'টাকার তাগাদা': 'Payment reminders',
  'বন্ধ': 'Off',
  'যেদিন দিতে হবে': 'On the day itself',
  'একদিন আগে': 'One day before',
  'তিনদিন আগে': 'Three days before',
  'কিছু মনে করাবে না': 'It will not remind you',
  'তাগাদা বন্ধ করা হল': 'Reminders turned off',
  '{0}টা তাগাদা রাখা হল': '{0} reminders set',
  'কাকে টাকা দিতে হবে আর কার কাছ থেকে পাওনা আছে — তারিখ এলে ফোন নিজেই মনে করিয়ে দেবে। সকাল ৯টায়।':
    'Who has to be paid and who owes you — the phone says so on the day, at nine in the morning.',
  'এখন যা যা মনে করানো হবে': 'What is queued now',
  'এখন কোনো তারিখ বাকি নেই।': 'No dates pending.',
  'টাকা দেওয়ার দিন': 'A payment is due',
  'টাকা পাওয়ার দিন': 'A payment is due to you',
  '{0} — {1} দিতে হবে': '{0} — {1} to pay',
  '{0} — {1} পাওনা আছে': '{0} — {1} owing to you',
  'মনে করিয়ে দেওয়ার অনুমতি দেওয়া হয়নি': 'Notification permission was not given',
  'এই ফোনে মনে করিয়ে দেওয়া চালু করা গেল না': 'Reminders could not be set up on this phone',

  /* ---- the phone book ---- */
  'ফোনের তালিকা থেকে': 'From the phone book',
  'তালিকা আনা হচ্ছে…': 'Loading…',
  'এই নামে কিছু পাওয়া গেল না।': 'Nothing found by that name.',
  'নাম খুঁজুন': 'Search a name',
  'নাম বা ফোন খুঁজুন': 'Search name or phone',
  'ফোনের নামের তালিকা দেখার অনুমতি দেওয়া হয়নি': 'Permission to read contacts was not given',
  'এই ফোনে নামের তালিকা পড়া গেল না': 'Contacts could not be read on this phone',
  'ফোন (ইচ্ছে হলে)': 'Phone (optional)',
  'সব': 'All',

  /* ---- factory reset ---- */
  'বিপজ্জনক': 'Dangerous',
  'সব মুছে নতুন করে শুরু': 'Erase everything and start again',
  'ফোন আর অনলাইন খাতা — দুটোই খালি হয়ে যাবে': 'The phone and the online ledger both go empty',
  'সব হিসাব, সব নাম, সব মজুত মুছে যাবে। ফেরানোর কোনো উপায় নেই — আগে সেটিংস → ব্যাকআপ থেকে একটা কপি রেখে দিন।':
    'Every entry, every name, all the stock goes. There is no way back — take a copy from Settings → Backup first.',
  'গোপন কোড': 'Secret code',
  'অনলাইন খাতাও মুছে দিন': 'Erase the online ledger too',
  'সার্ভারের কপিও খালি হবে': 'The server copy is emptied as well',
  'শুধু এই ফোন খালি হবে': 'Only this phone is emptied',
  'মুছে ফেলুন': 'Erase',
  'মোছা হচ্ছে…': 'Erasing…',
  'হ্যাঁ, সব মুছে দিন': 'Yes, erase everything',
  'কোড মিলল না': 'The code did not match',

  /* ---- stages, weights, wages ---- */
  'ধাপ মানে একটা বাড়ি তোলার পর্বগুলো — ভিত, কলাম, ছাদ, প্লাস্টার। রোজকার হিসাবে ‘কাজ কতদূর’ জিজ্ঞেস করার সময় আপনি শুধু বলেন কোন ধাপটা শেষ হল; শতকরা কত হল তা এখান থেকে বেরোয়।':
    'Stages are the phases of putting a house up — footing, columns, roof, plaster. In the evening you only say which stage finished; the percentage comes from here.',
  'থাম্ব রুল মানে প্রতি বর্গফুটে কত মাল লাগে — যেমন ০.৪ বস্তা সিমেন্ট। নতুন কাজের দর বানানোর সময় এটাই ব্যবহার হয়।':
    'A thumb rule is how much material a square foot takes — 0.4 bags of cement, say. It is what a new quote is built from.',
  'এই ধাপটা গোটা কাজের কত ভাগ?': 'What share of the whole job is this stage?',
  'সব ধাপের ভাগ যোগ করলে ১০০ হওয়া চাই। ছাদ ঢালাই গোটা কাজের প্রায় এক-পঞ্চমাংশ হলে এখানে ২০ বসান।':
    'All the shares must add up to 100. If the roof casting is about a fifth of the job, put 20 here.',
  '(ওজনের যোগফল {0}, ১০০ হওয়া দরকার)': '(shares add to {0}, they must make 100)',
  'একদিনের মজুরি (টাকা)': 'A day of work (₹)',
  'নাম, আর একদিন কাজ করলে কত টাকা পায়। যতজন মনে আছে দিন, বাকিরা পরে যোগ হবে।':
    'Name, and what he gets for one day of work. Add whoever comes to mind; the rest can follow later.',
  'দিনে ₹': '₹ a day',
  'দিনে {0}': '{0} a day',
  'আধা দিন বা ওভারটাইম দিতে নামের উপর চেপে ধরুন।': 'Press and hold a name for half day or overtime.',
  '{0} দিন × {1}': '{0} days × {1}',
  ' · অগ্রিম {0}': ' · advance {0}',
  ' · এরপর {0}': ' · then {0}',
  ' · বাকি': ' · on credit',
  '{0} কত {1}?': 'How many {1} of {0}?',
  '{0} দর কত?': 'What rate for {0}?',
  'গতবারের থেকে {0}% বেশি।': '{0}% more than last time.',
  '{0} — কত?': '{0} — how much?',
  'খাতায় ছিল {0}': 'The books said {0}',
  'খাতার থেকে {0} {1}। কোনো খরচ লিখতে ভুলে গেছেন কি?': '{0} {1} than the books. Did an expense go unwritten?',
  'আজ মাল আসেনি': 'No material today',
  'আর কোনো খরচ নেই': 'No other spending',
  '{0} — মজুরি': '{0} — wages',
  '{0} লাইন': '{0} rows',
  'এখন নেই': 'not now',

  /* ---- item sizes and types ---- */
  'মাপ বা ধরন (থাকলে)': 'Size or type (if any)',
  'ইঞ্চি': 'Inches',
  'মিলিমিটার': 'Millimetres',
  'মাপ নামের সঙ্গেই থাকে, তাই ১" আর ২" পাইপের মজুত আলাদা করে গোনা হয়।':
    'The size stays part of the name, so 1-inch and 2-inch pipe are counted as separate stock.',

  /* ---- the estimator ---- */
  'ধাপে ধাপে জিজ্ঞেস করা হবে — মাপ, ভিত, মাল, মজুরি, তারপর লাভ।':
    'It asks step by step — size, foundation, material, labour, then margin.',
  'এক তলার মাপ কত বর্গফুট?': 'How many square feet is one floor?',
  'একটা তলার বিল্ট-আপ মাপ। তলার সংখ্যা নিচে বসালে মোট মাপ নিজে থেকেই বেরোবে।':
    'The built-up area of a single floor. Put the number of floors below and the total works itself out.',
  'কতগুলো তলা': 'How many floors',
  'তলা': 'floors',
  'মোট বিল্ট-আপ {0} বর্গফুট': 'Total built-up {0} sqft',
  'ভিত কী ধরনের?': 'What kind of foundation?',
  'সাধারণ ফুটিং': 'Ordinary footing',
  'র‍্যাফট / ম্যাট': 'Raft / mat',
  'পাইলিং': 'Piling',
  'জানা নেই': 'Not known yet',
  'ভিত': 'Foundation',
  'ভিতের জন্য আলাদা খরচ (জানা থাকলে)': 'Separate cost for the foundation (if known)',
  'মাটি কাটা, পাইলিং, ঢালাইয়ের ঠিকা — যেটা আলাদা দিতে হয়। না জানলে ছেড়ে দিন, নিচের মালের হিসাবে ভিতের মালও ধরা আছে।':
    'Excavation, piling, a casting contract — whatever is paid separately. Leave it if unknown; the material below already covers the foundation.',
  'পরিমাণ আসছে আপনার নিজের থাম্ব রুল থেকে, দর আসছে আপনি শেষবার যা দিয়েছেন তা থেকে। আজকের বাজারদর আলাদা হলে এখানেই বদলে দিন।':
    'Quantities come from your own thumb rules and rates from what you last paid. If the market has moved, change them right here.',
  'দর': 'Rate',
  'মজুরির হিসাব': 'Labour estimate',
  'মজুরি কীভাবে ধরবেন?': 'How do you want to count labour?',
  'রোজের হিসাবে': 'By the day',
  'কতজন মিস্ত্রি-জোগাড়ে, কতদিন, দিনে কত': 'How many men, how many days, how much a day',
  'বর্গফুটের হিসাবে': 'By the square foot',
  'ঠিকা দরে কাজ দিলে': 'When the work is given on contract',
  'আপনার আগের কাজে {0} প্রতি বর্গফুট': 'Your past jobs came to {0} per sqft',
  'কারা কাজ করবে': 'Who will work',
  'এটা এই কাজের আন্দাজ — আপনার এখনকার লোকের তালিকার সঙ্গে এর কোনো সম্পর্ক নেই।':
    'This is a guess for this job — it has nothing to do with your current list of men.',
  'কী কাজ — যেমন রাজমিস্ত্রি': 'What trade — mason, say',
  'কতজন': 'How many',
  '+ কাজের লোক যোগ করুন': '+ Add a trade',
  'কত দিন কাজ চলবে': 'How many days the work runs',
  'দিনের সংখ্যা না বসালে মজুরি শূন্য থেকে যাবে।': 'Without a number of days the labour stays at zero.',
  '{0} জন × {1} দিন × {2} = {3}': '{0} men × {1} days × {2} = {3}',
  'গাড়ি ভাড়া, মেশিন, জল-বিদ্যুৎ, প্ল্যান পাশ — যা যা আলাদা লাগবে। যেগুলো লাগবে না, ছেড়ে দিন।':
    'Transport, machines, water and power, plan sanction — whatever else is needed. Leave out what is not.',
  '+ খরচ যোগ করুন': '+ Add a cost',
  'কীসের খরচ': 'What for',
  'প্ল্যান পাশ': 'Plan sanction',
  'লাভ ও মোট': 'Margin and total',
  'অনিশ্চয়তার জন্য %': 'Contingency %',
  'অনিশ্চয়তা {0}%': 'Contingency {0}%',
  'অনিশ্চয়তা {0}%     {1}': 'Contingency {0}%     {1}',
  'অন্য খরচ          {0}': 'Other costs          {0}',
  'কাজ: {0} · {1} তলা · মোট {2} বর্গফুট': 'Job: {0} · {1} floors · {2} sqft in all',
  'ভিত: {0}': 'Foundation: {0}',
  'সময়: প্রায় {0} দিন': 'Time: about {0} days',
  'প্রতি বর্গফুট {0}': '{0} per sqft',
  '{0} দিন': '{0} days',
  'খাড়া দাগটা কাজের অগ্রগতি — {0}%। তার ডানদিকে যা আছে, কাজের তুলনায় সেটা বেশি খরচ হচ্ছে।':
    'The upright line is progress — {0}%. Anything to the right of it is running ahead of the work.',
  'Site Khata · {0} · হিসাব আগে ফোনে লেখা হয়, তারপর খাতায় ওঠে।':
    'Site Khata · {0} · entries are written on the phone first, then reach the ledger.',
  '+ নিজে লিখুন': '+ Write your own',
  'বসান': 'Use it',
  'তুলে নিন': 'remove',
  'যোগ হবে — {0} ({1})': 'Will be added as {0} ({1})',
  'ফোনের তালিকা খোলা গেল না। নামটা নিজে লিখে নিন।': 'The phone book would not open. Type the name instead.',
  'ফোনে কোনো নাম পাওয়া গেল না': 'No names found on this phone',
  'ওই নামের সঙ্গে কোনো নম্বর পাওয়া গেল না': 'That contact has no phone number',
  'কারণ জানা গেল না': 'no reason given',
}
