/* The D1 schema is generated from the same column list the app serialises
   rows with, so the phone and the database cannot drift apart. Run this
   whenever SHEET_COLUMNS changes; the output is committed. */

import fs from 'node:fs/promises'

const src = await fs.readFile('src/lib/model.ts', 'utf8')
const block = src.match(/export const SHEET_COLUMNS[^{]*\{([\s\S]*?)\n\}/)
if (!block) throw new Error('SHEET_COLUMNS not found in src/lib/model.ts')

const TABLES = {}
for (const line of block[1].split('\n')) {
  const m = line.match(/^\s*(\w+):\s*\[(.*)\],\s*$/)
  if (!m) continue
  TABLES[m[1]] = m[2].split(',').map((s) => s.trim().replace(/^'|'$/g, '')).filter(Boolean)
}

const REAL = new Set([
  'amount', 'qty', 'rate', 'days', 'advance', 'weight', 'per_sqft', 'budget',
  'area_sqft', 'plan_days', 'seq', 'stage_seq', 'pct', 'terms_days', 'last_rate',
  'cash_counted', 'cash_computed',
])
const INT = new Set(['paid', 'personal', 'active'])

const APPEND = ['Day', 'Attendance', 'Stock', 'Money', 'Progress']
const type = (c) => (REAL.has(c) ? 'REAL' : INT.has(c) ? 'INTEGER' : 'TEXT')

const out = [
  '-- Generated by scripts/gen-schema.mjs from src/lib/model.ts — do not edit by hand.',
  '',
  'CREATE TABLE IF NOT EXISTS households (',
  '  id           TEXT PRIMARY KEY,',
  '  name         TEXT NOT NULL,',
  '  device_token TEXT NOT NULL UNIQUE,',
  '  created_at   TEXT NOT NULL',
  ');',
  '',
  '-- The nightly file, kept beside the data it describes so the app fetches',
  '-- both from one origin.',
  'CREATE TABLE IF NOT EXISTS briefs (',
  '  household_id TEXT NOT NULL PRIMARY KEY,',
  '  body         TEXT NOT NULL,',
  '  generated_at TEXT NOT NULL,',
  '  received_at  TEXT NOT NULL',
  ');',
  '',
]

for (const [tab, cols] of Object.entries(TABLES)) {
  const isAppend = APPEND.includes(tab)
  out.push(`CREATE TABLE IF NOT EXISTS ${tab.toLowerCase()} (`)
  out.push('  household_id TEXT NOT NULL,')
  for (const c of cols) {
    if (c === 'id') continue
    out.push(`  ${c.padEnd(12)} ${type(c)},`)
  }
  out.push('  id           TEXT NOT NULL,')
  out.push('  received_at  TEXT NOT NULL,')
  // The primary key is what makes a retried write a no-op rather than a
  // duplicate day — the database enforces it, not application code.
  out.push('  PRIMARY KEY (household_id, id)')
  out.push(');')
  if (isAppend) {
    out.push(`CREATE INDEX IF NOT EXISTS ix_${tab.toLowerCase()}_hd ON ${tab.toLowerCase()} (household_id, date);`)
    out.push(`CREATE INDEX IF NOT EXISTS ix_${tab.toLowerCase()}_hp ON ${tab.toLowerCase()} (household_id, project_id);`)
  }
  out.push('')
}

await fs.writeFile('server/schema.sql', out.join('\n'))
await fs.writeFile('server/src/columns.js',
  '// Generated by scripts/gen-schema.mjs — the one definition both sides share.\n' +
  'export const COLUMNS = ' + JSON.stringify(TABLES, null, 2) + '\n\n' +
  'export const APPEND_TABS = ' + JSON.stringify(APPEND) + '\n')
console.log('wrote server/schema.sql and server/src/columns.js —', Object.keys(TABLES).length, 'tables')
