import { chromium } from 'playwright'
import { createServer } from 'vite'
const server = await createServer({ server: { port: 5197 } }); await server.listen()
const b = await chromium.launch(process.env.PW_CHROMIUM ? { executablePath: process.env.PW_CHROMIUM } : {})
const page = await b.newPage({ viewport: { width: 400, height: 860 }, deviceScaleFactor: 2 })
const t = async s => { await page.getByText(s).first().click(); await page.waitForTimeout(220) }
await page.goto('http://localhost:5197/'); await page.waitForTimeout(700)
await t('শুরু করি')
await page.locator('input.input').first().fill('রামপুর বাড়ি')
await page.locator('input.input').nth(1).fill('2800000')
await t('এগিয়ে যান')
const men = [['রতন মণ্ডল','600'],['সুকুমার দাস','550'],['হারাধন','700'],['বিশু','500']]
for (let i=0;i<men.length;i++){
  if(i) await t('+ আরও একজন')
  await page.locator('input.input').nth(i*2).fill(men[i][0])
  await page.locator('input.input').nth(i*2+1).fill(men[i][1])
}
await page.locator('.input.num').last().fill('52000')
await t('হয়ে গেল'); await page.waitForTimeout(900)

// one full day so the dashboard has something honest on it
await t('আজকের হিসাব'); await page.waitForTimeout(300)
for (const i of [0,1,2]) await page.locator('.pick').nth(i).click()
await page.screenshot({ path: 'scripts/shot-2-attendance.png' })
await t('এগিয়ে যান')
await page.screenshot({ path: 'scripts/shot-3-wages.png' })
await t('এগিয়ে যান'); await t('হ্যাঁ')
await page.getByText('সিমেন্ট', { exact: true }).first().click(); await page.waitForTimeout(200)
for (const d of ['১','০']) await page.locator('.pad button', { hasText: d }).first().click()
await t('এগিয়ে যান')
for (const d of ['৪','১','০']) await page.locator('.pad button', { hasText: d }).first().click()
await page.getByText('+ দোকান যোগ করুন').click()
await page.locator('.sheet input.input').first().fill('শর্মা ট্রেডার্স')
await page.locator('.sheet .input.num').first().fill('15')
await page.locator('.sheet .btn.primary').click(); await page.waitForTimeout(200)
await t('না, বাকি')
await page.screenshot({ path: 'scripts/shot-4-rate.png' })
await page.getByText('যোগ করুন', { exact: true }).last().click(); await page.waitForTimeout(250)
await t('এগিয়ে যান')
await t('হ্যাঁ')
await page.locator('.chip').first().click(); await page.waitForTimeout(200)
for (const d of ['৮','০','০']) await page.locator('.pad button', { hasText: d }).first().click()
await t('যোগ করুন'); await t('এগিয়ে যান')
await page.getByText('অর্ধেক হয়েছে').first().click(); await page.waitForTimeout(250)
await page.screenshot({ path: 'scripts/shot-6-cash.png' })
await page.getByText('না, গুনে বলছি').click(); await page.waitForTimeout(200)
for (const d of ['৪','৩','৮','০','০']) await page.locator('.pad button', { hasText: d }).first().click()
await t('ঠিক আছে'); await page.waitForTimeout(250)
await page.screenshot({ path: 'scripts/shot-6b-variance.png' })
await t('এগিয়ে যান')
await page.screenshot({ path: 'scripts/shot-7-review.png' })
await t('সেভ করুন'); await page.waitForTimeout(900)
await page.screenshot({ path: 'scripts/shot-1-home.png', fullPage: true })
await b.close(); await server.close()
console.log('shots done')
